# Generated by Django 4.1 on 2022-09-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_watchlist_delete_mywatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
